name: Deploy to ECS

on:
  push:
    branches:
      - main
    paths:
      - 'simple_ecs/ecspresso/**'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::996109426400:oidc-provider/token.actions.githubusercontent.com
        aws-region: ap-northeast-1

    - name: Install ecspresso
      uses: kayac/ecspresso@v2
      with:
        version: latest

    - name: Deploy to ECS
      run: ecspresso deploy --config simple_ecs/ecspresso/ecspresso.yml
